name: MacOS
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12, 14, 16, 18, 20]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
      env:
        CI: true
